#!/bin/sh

# whichpower is script of CBA "CBA Battery Available" collection
#
# Copyright 2003 Marco Massari Calderone <M.Calderone@CS.UniBO.IT>
#
# --------------------------------------------------------------------------
# - This script is free software; you can redistribute it and/or modify it -
# - under the terms of the GNU General Public License as published by the  -
# - Free Software Foundation; either version 2, or (at your option) any    -
# - later version.                                                         -
# -                                                                        -
# - This script is distributed in the hope that it will be useful, but     -
# - WITHOUT ANY WARRANTY; without even the implied warranty of             -
# - MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU      -
# - General Public License for more details.                               -
# --------------------------------------------------------------------------
# return values:
#
# 255 -- undeterminable
# 0   -- apm
# 1   -- acpi
# 2   -- pmu

if [ -f /proc/apm ]; then exit 0;fi
if [ -d /proc/acpi ]; then exit 1;fi
if [ -d /proc/pmu ]; then exit 2;fi
exit 255;
